package com.example.desafiosetup.adapter.output.dynamodb.entidade

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.example.desafiosetup.aplicacao.dominio.constante.Status
import java.math.BigDecimal
@DynamoDBTable(tableName = "ContaCorrente")
data class TransferenciaModel (
    @DynamoDBHashKey(attributeName = "pk")
    var pk: String = "",
    @DynamoDBRangeKey(attributeName = "sk")
    var sk: String = "",
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    var timestamp: String? = null,
    @DynamoDBTypeConvertedEnum()
    var status: Status = Status.PENDENTE,
    @DynamoDBAttribute(attributeName = "valor")
    var valor: BigDecimal,
    @DynamoDBAttribute(attributeName = "caminho_s3")
    var caminhoS3: String
){
    init {
        this.pk = "TRANSFERENCIA_" + this.pk
    }
}