package com.example.desafiosetup.adapter.output.dynamodb

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.example.desafiosetup.aplicacao.dominio.modelo.Correntista

@DynamoDBTable(tableName = "ContaCorrente")
data class CorrentistaModel(
    @DynamoDBHashKey(attributeName = "pk")
    var pk: String = "",
    @DynamoDBHashKey(attributeName = "sk")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    var sk: String? = null,
    @DynamoDBHashKey(attributeName = "nome")
    val nome: String,
    @DynamoDBHashKey(attributeName = "conta")
    val conta: String
) {
    fun toCorrentista() = Correntista(
            nome = nome,
            conta = conta
    )
}

fun Correntista.toCorrentista() = CorrentistaModel(
        nome = nome,
        conta = conta
)